services:
  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=MyVerySecretKey
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://superset:secretsecret@database:5432/superset
    ports:
      - '8080:8088'
    depends_on:
      - database

  database:
    image: postgres:alpine
    container_name: superset_db
    environment:
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=secretsecret
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
